use_frameworks!

target 'SHSearchBar_Example' do
  pod 'SHSearchBar', :path => '../'

  target 'SHSearchBar_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
